### ISSUE TITLE
Proposal Preview page - entered options and description data not visible 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#107]
**Description**
I've created Contributor proposal with two options, each option has one 'Transfer&Mint' action, that is, trasnsfering 10 SWPR tokens to given account address. Options should read "First option" and "Second Option"

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Click on newly created Proposal

**Expected behavior**
Should see description, name of the options that were set while creating the proposal.

**Screenshots**
![dao1](https://user-images.githubusercontent.com/37701286/177431849-14be3f65-1622-460a-9720-9e26546d66e7.png)
![dao2](https://user-images.githubusercontent.com/37701286/177431735-236f8d80-dacf-4c1b-8484-ca064a5cec44.png)
![dao3](https://user-images.githubusercontent.com/37701286/177431750-10440885-e557-4757-8da3-c173a31080c7.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
I have noticed that this happens from time to time when I create new contributor proposal, does not work after page refresh

**Comment by rossneilson** [comment]
Could you test this again to see if it is still an issue?

**Comment by Filipv95** [comment]
@rossneilson everything seems fine, I'm unable to reproduce this anymore.

**Comment by Filipv95** [comment]
@rossneilson I've managed to reproduce this bug again after creating several new Proposals, since steps are always the same it's hard to point out what the problem is, perhaps someone should take a look again.
