### ISSUE TITLE
Unable to join the SWPR guild from first attempt

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#108]
**Description**
Sometimes happens that after successful transaction, my power is not increased, I still see Join button and transaction is visible under 'Recent transactions'

**Steps to Reproduce**
"1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Check if all Guilds are displayed at Landing Page
5. Go to SWPRGuild Page
6. Click on Join button
7. Enter amount of SWPR in Balance field
8. Click Approve SWPR Spending
9. Click to Confirm transaction on MetaMask
10. Check if Lock [amount] SWPR tokens transaction appears under recent transactions "

**Expected behavior**
Should see change on SWPR token balance, power should increase, join button should dissapear 
 
**Screenrecord**
https://user-images.githubusercontent.com/37701286/177490383-584f90cc-f27b-4570-bed8-fd2aa69ec204.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
For DXDGuild this is not the case, change is noticeabe right away.

**Comment by rossneilson** [comment]
I think if you refresh the page it would then show, alternatively waiting should eventually update the UI.
#53 should fix this as we need to increase frequency of checks or manually refresh the data
