### ISSUE TITLE
Getting different voting power percentage, for the same amount of tokens, for different users

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#109]
**Description**
Tried with accounts [0, 1, 2] from Mnemonic accounts list - these are the accounts that initially have set SWPR token amounts, in dev.ts file  

**Steps to Reproduce**
"1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Check if all Guilds are displayed at Landing Page
5. Go to SWPRGuild Page
6. Click on Join button
7. Enter amount of SWPR in Balance field
8. Check the calculated Voting power

**Expected behavior**
Same amount of tokens entered in balance field, should result same voting power percentage  

**Screenrecords**
Account 0:
https://user-images.githubusercontent.com/37701286/177492282-2aa2e773-8f45-4947-9a6e-1c8e6333a7f1.mp4
Account 1:
https://user-images.githubusercontent.com/37701286/177492323-83cac964-e938-45b5-8cd6-aa4f49e98325.mp4
Account 2:
https://user-images.githubusercontent.com/37701286/177492344-7ef02211-966c-47db-be49-4ce835242b58.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Notice that account 2 for any entered value gets 100% voting power.

**Comment by rossneilson** [comment]
If you refer to the number of members in the top left you can see it is different in each screen recording. The way percentage is worked out is:
Current user locked tokens / Total tokens locked

So if there are more users locked already then voting power will be smaller and if there are no users and you lock tokens you will always have 100% until someone else locks tokens.

From the recording I think all of these are correct and this can be closed?

**Comment by Filipv95** [comment]
Thank you Ross, ack, that is the case, this can be closed.
