### ISSUE TITLE
REPGuild - Remove withdraw tokens button

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#112]
**Description**
When I try to withdraw tokens I get rejected, also tried reseting account on metamask 
Notice how guild is unable to load my voting power percentage - tried refreshing several times

**Steps to Reproduce**
1. SpinUp Localhost env 
2. Open localhost:3000 
3. Check if Landing Page is loaded 
4. Click on REPuild box 
5. Click on Withdraw 

**Expected behavior**
Unlock and withdraw tokens from REPGuild

**Actual behavior**
Unable to withdraw tokens from REPGuild

**Screenshots**
![rep](https://user-images.githubusercontent.com/37701286/177821119-1295d82e-5f06-4de2-a759-e0b0313e91a5.png)
![rep2](https://user-images.githubusercontent.com/37701286/177821200-c6cca4b3-7087-4489-bb5f-4d35c30475b8.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Tried with different accounts, getting same behaviour. On other Guilds this is not the case.

**Comment by rossneilson** [comment]
The REP guild is a type of guild similar to DXdao where non transferable tokens are used, so in this case we want to remove the button if the guild is a rep guilds

**Comment by Filipv95** [comment]
Ack, thank you Ross.

**Comment by rossneilson** [comment]
Hoping this is out of date bytecode issue

**Comment by Filipv95** [comment]
@rossneilson I've check this again, it's still looks the same. 
- Click on 'Withdraw' button > Transaction Rejected
- Click on 'Increase Voting Power' > redirects to White page
