### ISSUE TITLE
Figma - Stake tokens popup window isn't like by Figma design (Mobile response)

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#119]
**Description**
Stake tokens popup window is different than Figma desing. Things to look out for:
- Balance fields
- Min deposit field
- Final button

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Join button at left box menu at Guild page

**Expected behavior**
- Min deposit is displayed
- Balance is displayed one time
- The button says 'Continue'
<img width="360" alt="expected" src="https://user-images.githubusercontent.com/37701286/178012483-de2c00ea-4667-4a66-90d0-a742beacb4f5.png">

**Actual behaviour**: 
- Min deposit isn't displayed
- Balance is displayed two times
- The button says 'Lock SWPR'
<img width="364" alt="actual" src="https://user-images.githubusercontent.com/37701286/178012464-ae71f49a-8eaf-4f2c-b339-4d156938ca87.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
The additional balance is fine and some of this data doesn't exist, the design for this is very old so going to close
