### ISSUE TITLE
Change button should open Metamask and allow me to change to different address

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#121]
**Description**
Given I want to change currently connected account, and I click on Account address on top-right corner, click on Change button and select Metamask. Metamask should open so that I can select different accoutn to connect.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Check if SWPRGuild page is opened
6. Click on Connect wallet button in the upper right corner of the Guilds Landing Page
7. Click on Metamask option
8. Confirm transaction on Metamask
9.  Click on account address icon on top-right corner
10. Click on Change button
11. Click on Metamask option

**Expected behavior**
Metamask extension should open so I can select different account to connect

**Screenrecord**
https://user-images.githubusercontent.com/37701286/178016415-337ce5ab-54f0-47cb-8e56-53cd31d19d38.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Is this normal behaviour in other apps, I am not sure I have used this before?

**Comment by Filipv95** [comment]
IMO this is not expected behaviour 'cause some other app that I used and when I switch network in app automatically MetaMask ask me to switch to another network and when I approve, then I can see at app that network is changed.

**Comment by rossneilson** [comment]
Bit of a difference here with network and account. Network switching is done via metamask if you click on the network tab. The original description was about changing accounts, but not sure this is something we should handle, more a wallet function.

**Comment by Filipv95** [comment]
Yes, maybe this is happening because of Local env so I think it's ok for now.
