### ISSUE TITLE
Proposal Preview page - Says proposal is active but I am unable to vote 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#122]
**Description**
I've create a Contributor proposal with two options ('First', 'Second'), which have Transfer&Mint action, when I go to newly created Proposal and try to vote I get rejected even though proposal has 'Active' status.  

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Check if SWPRGuild page is opened
6. Connect Wallet
7. Click on Create Proposal button
8. Create Contributor Proposal with two options
9. Add Transfer&Mint actions to both Options
10. Finish creating Proposal and approve transaction on Metamast
11. Go to newly created Proposal Page
12. Vote for First option 

**Expected behavior**
Should be able to successfully vote for selected option if I have power, and Proposal has 'Active' status

**Screenrecord**
https://user-images.githubusercontent.com/37701286/178026437-e06f4c36-a48c-4551-a850-223ad12a34a9.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Tried to vote with account that is the creator of the proposal
Is there something I am missing here, perhaps some configuration or anything like that?

**Comment by Filipv95** [comment]
<img width="1430" alt="Screenshot 2022-07-14 at 17 40 36" src="https://user-images.githubusercontent.com/37701286/179022035-3e76ee2e-c739-4f29-8a7b-9ae6230a2fbd.png">

When I try to vote on Proposal I got Rejected status and in console requests are spinning in loop.

**Comment by rossneilson** [comment]
Is this still replicatable, the error suggests RPC issues which is strange on localhost

**Comment by Filipv95** [comment]
@rossneilson yes it is, check this screen record

https://user-images.githubusercontent.com/37701286/184917023-66cc75ac-ff8c-4643-9630-9c742b6f55b8.mp4

**Comment by rossneilson** [comment]
Ah this must be related to https://github.com/DXgovernance/dxdao-contracts/issues/206

**Comment by Filipv95** [comment]
@rossneilson ack, I'll check this flow again after merge of #206

**Comment by rossneilson** [comment]
Could we check this again @Filipv95 ?

**Comment by Filipv95** [comment]
@rossneilson this is no longer issue, every thing works as expected!
