### ISSUE TITLE
Proposal Preview page - unable to vote for myself

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#123]
**Description**
Initially created Contributor Proposal, changed the account and unsuccessfully tried to vote for myself with enought power, while Proposal had Active status. Also tried voting after reseting my account on Metamask.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Check if SWPRGuild page is opened
6. Connect Wallet
7. Click on Create Proposal button
8. Create Contributor Proposal with two options
9. Add Transfer&Mint actions to both Options
10. Finish creating Proposal and approve transaction on Metamast
11. Go to newly created Proposal Page
12. Vote for First option i.e myself

**Expected behavior**
Should be able to successfully vote for selected option if I have power, and Proposal has 'Active' status

**Screenrecord**
https://user-images.githubusercontent.com/37701286/178028668-cf2eae22-7c1f-4f14-af92-8c73440b77cc.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Filipv95** [comment]
If I understood correctlly, I should be able to vote for myself on a Proposal? @rossneilson

**Comment by rossneilson** [comment]
Correct we should I believe be able to

**Comment by dcrescimbeni** [comment]
Couldn't reproduce. 

I tried to vote for myself both from the same and another account, both votes were successful and correctly accounted for.

https://www.loom.com/share/2e5b6b389d144d71be4f86b22c14e468
