### ISSUE TITLE
Executed Proposal without being member of a Guild

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#124]
**Description**
I was able to Execute the Proposal without previously joining the Guild, in this case DXDGuild 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Check if SWPRGuild page is opened
6. Connect Wallet
7. Click on DXDGuild box
8. Click on Executable Proposal
9. Click on Execute button
10. Confirm transaction on Metamask

**Expected behavior**
In order to execute the proposal I should previously join particular Guild

**Screenrecord**
https://user-images.githubusercontent.com/37701286/178033612-e325b4eb-658c-4716-94ef-e1e584a745b2.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Filipv95** [comment]
Is this, perhaps a expected behavior? @rossneilson

**Comment by rossneilson** [comment]
This isn't enforced by the contracts so is expected behaviour
