### ISSUE TITLE
Explanation for Proposal failed status

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#125]
**Description**
When the Proposal executable time elapses Proposal should get 'Failed' status, also there should be an explanation for this status. 
 
**Steps to Reproduce**
1. Start Creating Contributor Proposal
2. Create two options 
3. Add Transfer&Mint action to each (use two different account addresses)
4. Finish creating proposal 
5. Confirm transaction on Metamask
6. Vote for first option (account that has not joined the SWPRGuild)
7. Wait for proposal to become executable
8. Wait for executable period to expire
9. Execute proposal

**Expected behavior**
Should get an explanation that the execution time has passed.

**Screenshots**
![notpartoftheguild](https://user-images.githubusercontent.com/37701286/178104392-684bba32-05ad-4a46-beb7-cc0b3af12274.png)
![failed](https://user-images.githubusercontent.com/37701286/178104420-28e93b42-7a72-4abd-9ca8-f1e81fd7bd6e.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Filipv95** [comment]
Account has not joined SWPRGuild, could this be the reason Proposal failed? Usually I get rejected status  @rossneilson

**Comment by rossneilson** [comment]
From the BaseERC20Guild.sol 
The winning action has a certain amount of time to be executed successfully if that time passes and the action didn't
  executed successfully, it is marked as failed.

**Comment by rossneilson** [comment]
We could turn this into an issue to add an explanation to the failed status stating that proposal execution time elapsed

**Comment by Filipv95** [comment]
@rossneilson ack, thank you, I have edited this issue

**Comment by rossneilson** [comment]
Added more info and scope to #229
