### ISSUE TITLE
Proposal rejected after execution

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#126]
**Description**
Created Contributor Proposal with two option two Transfer&Mint actions for each of them, successfully voted two times for first option, and after execution I got rejected status for Proposal.

**Steps to Reproduce**
1. Start Creating Contributor Proposal
2. Create two options 
3. Add Transfer&Mint action to each (use two different account addresses)
4. Finish creating proposal 
5. Confirm transaction on Metamaks
6. Vote for first option
7. Wait for proposal to become executable
8. Execute proposal

**Expected behavior**
Account that had more votes should receive deticated amount of SWPR tokens

**Screenshots**
![rejectedproposal](https://user-images.githubusercontent.com/37701286/178104606-b00c8c84-037b-48a6-bba3-74b24ed7e6b5.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
This time voting impact didnt show on the page, I voted two times for first option, all accounts were members of the SWPRGuild, and transactions was rejected

**Comment by rossneilson** [comment]
Could be realted to #63 lets revisit once this and new contracts are added

**Comment by Filipv95** [comment]
@rossneilson thank you, ack and agreed

**Comment by rossneilson** [comment]
Could we test this again?

**Comment by Filipv95** [comment]
@rossneilson Tested this once again. Did the same thing with one action (Transfer of 3 SWPR tokens), voted with 2 different account 'FOR' Proposal, as soon as it became 'Executable' I executed it and Proposal changed state to '**Failed**'. Should have changed status to '**Executed**', right?

![vote](https://user-images.githubusercontent.com/37701286/184687376-b1cd771e-61b5-4cf7-a43d-0b629dc561ec.png)

**Comment by rossneilson** [comment]
That should be correct due to permissions not being set beforehand, but good to see the votes coming in properly
