### ISSUE TITLE
Able to create Proposal with less power then required

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#127]
**Description**
Checked dev.ts file, **votingPowerForProposalCreation** is set to 5, I managed to create Contributor Proposal with 0.9% power

**Steps to Reproduce**
1. Start Creating Contributor Proposal from SWPRGuild page
2. Create two options 
3. Add Transfer&Mint action to each (use two different account addresses)
4. Finish creating proposal 
5. Confirm transaction on Metamaks
6. Check if newly created Proposal is displayed on SWPRGuild page

**Expected behavior**
I should not be able to create proposal with power coeficient lower that expected.

**Screenshots**
![votingpoverforproposalcreation](https://user-images.githubusercontent.com/37701286/178104799-b1808704-bcd4-434c-96f0-4a7096b4d0d5.png)
![votingpoverforproposalcreation1](https://user-images.githubusercontent.com/37701286/178104794-909df697-90e9-4113-b5ec-41f602fb9342.png)
https://user-images.githubusercontent.com/37701286/178104861-84cfa55c-d241-4254-9d8a-6105c18c8655.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Filipv95** [comment]
Does this number '5' in dev.ts files mean like 5% voting power is required to e.g. create Proposal? @rossneilson

**Comment by rossneilson** [comment]
From the contract:
// The percentage of voting power in base 10000 needed to execute a proposal action
    // 100 == 1% 2500 == 25%
