### ISSUE TITLE
Number of tokens within the Guild is not being updated

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#128]
**Description**
Transfer&Mint option - Initial number of tokens in SWPRGuild is 10, that number remains the same when I Lock new tokens or withdraw tokens with different account addresses. 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box
5. Check if SWPRGuild page is opened
6. Connect Wallet
7. Start creating Contributor Proposal
8. Create one option and add "Transfer&Mint" or "Vesting contract for token" option
9. Click on Asset (token) drop-down 

**Expected behavior**
The number of tokens within the Guild should change when new tokens are added or withdrawn

**Screenshots**
Initial token number:
![swprtokennumber](https://user-images.githubusercontent.com/37701286/178216395-acd1aa4a-8d49-4cbb-8d78-0194dd4be243.png)
Added 20 tokens: 
![swprtokennumberadded](https://user-images.githubusercontent.com/37701286/178216401-f1769369-c81c-4ab5-b84f-04d32c481ae4.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Currently, number of tokens withing the Guild can be visible on Asset drop-down for "Transfer&Mint" and "Vesting contract for token" options. Same behavior for DXDGuild.

**Comment by rossneilson** [comment]
The tokens locked are locked in a special contract and are not spendable by the guild. When a user locks tokens they still belong to them and the guild cannot just steal them. The amount transferable is the amount of tokens held directly by the guild contract. So if you were to send tokens directly to the guild address then this number would increase.
