### ISSUE TITLE
Able to create Proposal without entering all required data

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#131]
**User Story**
As I user I expect to see what fields I need to populate in order to create valid Proposal

**Alternative Solutions**
We should add validation for fields i.e. what fields are required for proposal to be valid and created successfully. 

**Screenrecord**
First didnt select any asset then select token with no value
https://user-images.githubusercontent.com/37701286/178307575-536a8014-f209-482b-ac3d-ee406aeffdc7.mp4

**Screenshot**
Didnt enter any address:
![actionswithnothing](https://user-images.githubusercontent.com/37701286/178307797-a745a138-9135-4560-9229-4e447a696b91.png)

**Additional context**
It is logical that you need all this data in order to create Proposal but IMO we should not allow user to come to situation where page breaks like on video.

**Comment by rossneilson** [comment]
Nice find, we need some more validation on inputs

**Comment by MiltonTulli** [comment]
@rossneilson @Filipv95 Created PR https://github.com/DXgovernance/DAVI/pull/149 for this. 
I included ONLY ERC20Transfer action validation. 
I think we should create diff issues to validate diff suportedActions: 
- ERC20Transfer (done)
- REP MINT
- Set Permissions
