### ISSUE TITLE
The user doesn't have to select the type of Proposal to create it

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#134]
**Description**
User should select one of Proposal types in order for the Continuous button to be clickable

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button

**Expected behavior**
If user don't select any Proposal type Continue button should be disabled 

**Screenshots**
<img width="1371" alt="Screenshot 2022-07-11 at 23 13 50" src="https://user-images.githubusercontent.com/37701286/178582204-ee0bb4a6-f8be-4c2e-9e66-29555b06af47.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
I'm considering removing this page entirely for the initial launch since we wont have any templates or types and so it is just wasting user's time
