### ISSUE TITLE
Displayed button 'Switch MetaMask To Localhost' while Localhost it is already set

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#136]
**Description**
When I spinUp Localhost and Landing Page is loaded then I see 'Switch MetaMask To Localhost' button next to 'Localhost' which means it is already set

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded

**Expected behavior**
I expect to see 'Connect wallet' button instead 'Switch MetaMask To Localhost' button

**Screenshots**
<img width="1440" alt="Screenshot 2022-07-12 at 23 10 36" src="https://user-images.githubusercontent.com/37701286/178596270-337bde56-1daf-49ab-bcac-15d76f43a39f.png">

<img width="1440" alt="Screenshot 2022-07-12 at 23 10 42" src="https://user-images.githubusercontent.com/37701286/178596111-c5f745b5-31b3-4ab1-803a-5ca7f66987a3.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by dcrescimbeni** [comment]
I think this got solved after switching to `wagmi`. It was a common occurrence, but can't reproduce it anymore.

**Comment by Filipv95** [comment]
Yeah, I'm also unable to reproduce it and test has passed successfully. This is old issue that we can close now, thank you @dcrescimbeni
