### ISSUE TITLE
Switch MetaMask To Localhost button and MetaMask extension aren't connected properly

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#140]
**Description**
'Switch MetaMask To Localhost' button open MetaMask extension but when I approve at extension that I want to switch network at app nothing happens. Also when I click on MetaMask extension and there manually change network then I can see my wallet address instead  'Switch MetaMask To Localhost' button.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on 'Switch MetaMask To Localhost' button
5. Click on 'Switch network' button at MetaMask extension

**Expected behavior**
When I click on 'Switch MetaMask To Localhost' button and approve at extension that I want to switch network I expect to be on Localhost and to see my wallet address.

**Screen record**

https://user-images.githubusercontent.com/37701286/179036468-248407c2-594b-4b9d-b728-b3689344fe4d.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by dcrescimbeni** [comment]
Related to issue #136 . I think this got solved after implementing `wagmi`.

Now you can change the network both from MetaMask or the UI, and both get sync'd.

I can't reproduce this anymore.

**Comment by Filipv95** [comment]
Test has passed successfully and now we can close the issue
