### ISSUE TITLE
Add native asset to asset lists

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#141]
We currenlty list all erc20 tokens the guild has but we also need to allow native asset transfers. 
This will require manually adding to the list but also dealing with separately as it doesn't call a contract but instead directly sets `to` to the receiver and `value` is the amount with `data` blank.

**Comment by dcrescimbeni** [comment]
Should the native token transfer be another option in the Action Builder? Like: 
- Transfer & Mint ERC20 tokens
- Transfer native token
- Set Permissions

Or should it be handled inside the "Transfer & Mint" action?

**Comment by rossneilson** [comment]
It should be handled inside transfer and mint. Similar to what you see in swapr, most people just view native token as another ERC20 token despite being different under the hood

**Comment by dcrescimbeni** [comment]
The current changes to the smart contract broke some of the functionality, so I'll wait until we have the final version that'll get sent to audit to continue developing this.
