### ISSUE TITLE
'Vesting contract for DXD token' action isn't display properly 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#142]
**Description**
When I add 'Vesting contract for DXD token' action I don't see informations about this actions. I only can see empty field.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Option
8. Click on Add Action button
9. Add 'Vesting contract for DXD token' action with all required data

**Expected behavior**
When I add 'Vesting contract for DXD token' action I expect to see information about this action

**Screenshots**
<img width="1396" alt="Screenshot 2022-07-16 at 13 16 27" src="https://user-images.githubusercontent.com/37701286/179352640-aee274d8-1dea-4d92-a3e2-f374a623c8cb.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
We need to update the rich contract ipfs file for this, we should also update the richContracts.json file to match.
To fix this bug we need to add string literals

**Comment by MiltonTulli** [comment]
@Filipv95 What do you think is a good label for this?
I added this but maybe not the best. 

`'Vesting contract of ${value}${tokenSymbol} starting ${start}'`
![Image](https://user-images.githubusercontent.com/25844967/181638546-eecbae92-82ef-4845-9582-5275a3e09ef5.png)

**Comment by Filipv95** [comment]
@MiltonTulli I like the label that you propose. Now, I have one more option that I think about and that is "Vesting of 1 DXD starting from 2022-07-19"
