### ISSUE TITLE
Proposal which include 'Vesting contract for DXD token' action crashes the application

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#143]
**Description**
When I create Proposal with 'Vesting contract for DXD token' action and I want to see it and to vote, I can't because page can't load and I got Error Page.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Create Proposal with 'Vesting contract for DXD token' action
7. Go to Landing Page
8. Click on SWPRGuild box

**Expected behavior**
I expect to see Proposal with all data and I expect to be able to vote at this Proposal.

**Screenshots**
<img width="1431" alt="Screenshot 2022-07-16 at 13 31 55" src="https://user-images.githubusercontent.com/37701286/179353122-57fc9f1b-8dc8-429b-ba69-6daee70a8766.png">
<img width="1431" alt="Screenshot 2022-07-16 at 13 32 41" src="https://user-images.githubusercontent.com/37701286/179353129-b601e44d-0c42-4100-87d4-2b48cd2d3d14.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Kenny-Gin1** [comment]
@Filipv95 I assigned this issue to myself. After looking through the code it crashes because the External Contracts have not been implemented as of yet.

**Comment by Kenny-Gin1** [comment]
Hm, I spoke hastily. It has been implemented!

**Comment by Kenny-Gin1** [comment]
Ok, as far as the crashing goes now, it's fixed. However, we need to upload the latest richContracts containing ´templateLiterals´ to our IPFS node so that the right information is displayed. @rossneilson

**Comment by MiltonTulli** [comment]
@Kenny-Gin1 I updated ipfs file with 'templateLiteral' keys  here https://github.com/DXgovernance/DAVI/pull/169

**Comment by Filipv95** [comment]
@rossneilson I have reproduced this bug again, after approving transaction on Metamask I'm redirected to white page (check screenrecord), after this when I go to SWPR guild page I can se newly created Proposal with Active state.

https://user-images.githubusercontent.com/37701286/182656490-aab3302e-ca9a-43ea-baa0-f8b9fc850b89.mp4
