### ISSUE TITLE
'Global Permission Registry' action isn't display properly

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#153]
**Description**
When I add 'Global Permission Registry' action I don't see informations about this actions. I only can see empty field.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Option
8. Click on Add Action button
9. Add 'Global Permission Registry' action with all required data

**Expected behavior**
When I add 'Global Permission Registry' action I expect to see information about this action

**Screenshot**
<img width="1432" alt="Screenshot 2022-07-22 at 00 03 50" src="https://user-images.githubusercontent.com/37701286/180322908-1e1c3bfd-f955-4bd7-befb-b31e654e3b0b.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Lets fix this in #145 Should be simple

**Comment by rossneilson** [comment]
Check after merging https://github.com/DXgovernance/DAVI/pull/169/

**Comment by Filipv95** [comment]
@rossneilson I've checked this again, it's been fixed, the text is showing but I am unable to finish creating proposal, I've logged this behavior as separate issue #188 
IMO we can close this one.
