### ISSUE TITLE
User can't create Proposal which include 'Global Permission Registry' action

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#155]
**Description**
When I want to create Proposal with 'Global Permission Registry' action and click on 'Create Proposal' button, then nothing happens on the FE and I see errors in the console.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Option
8. Click on Add Action button
9. Add 'Global Permission Registry' action with all required data
10. Click on 'Create Proposal' button

**Expected behavior**
I expect the Proposal should be created with all data and I expect to be able to vote at this Proposal.

**Screenshots**
<img width="1435" alt="Screenshot 2022-07-22 at 17 01 57" src="https://user-images.githubusercontent.com/37701286/180468715-c09cc2c3-19a8-4c24-a895-fdff9a3a681e.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Also adding this to #145 as it refactors a lot of how we do permissions
Likely this issue is because we updated contracts and should be fixed by the related issue
