### ISSUE TITLE
Proposal which include 'NFT Factory' action didn't displayed properly at SWPRGuild page

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#156]
**Description**
When I create Proposal with 'NFT Factory' action, at SWPRGuild page I don't see informations about action. I only can see empty  action field for this this proposal.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Option
8. Click on Add Action button
9. Add 'NFT Factory' action with all required data
10. Click on 'Create Proposal' button
11. Go to Landing Page
12. Click on SWPRGuild box

**Expected behavior**
When I create Proposal with 'NFT Factory' action, at SWPRGuild page I expect to see Proposal with all informations for actions
eg When I enter to Proposal I can see informations for 'NFT Factory' action (Screenshot 2)

**Screenshots**
<img width="1435" alt="Screenshot 2022-07-23 at 00 16 27" src="https://user-images.githubusercontent.com/37701286/180576502-c42fa52e-8313-4b88-8262-90f1300a30fa.png">
<img width="1435" alt="Screenshot 2022-07-23 at 00 22 41" src="https://user-images.githubusercontent.com/37701286/180576531-a18f7d58-5bb7-4f02-9a72-ed59cb6d1131.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Looks like we are not dealing with generic calls properly in the short summary

**Comment by Filipv95** [comment]
@rossneilson I've checked this issue again after merge of #193, same thing like for issue #191 

Can you confirm that this is expected look?
![asdf](https://user-images.githubusercontent.com/37701286/183480411-943d8377-cdc5-48a5-be4a-763420420cd7.png)
![asdf2](https://user-images.githubusercontent.com/37701286/183480421-71dad45c-12db-4167-bb80-13739545e471.png)

**Comment by rossneilson** [comment]
Yes this is correct, we could show the big long string here but really but just want to show high level what is happening so the function titles is what we show in proposal card. I believe in code we refer to it as a compact view

**Comment by Filipv95** [comment]
@rossneilson ack, thank you!

**Comment by Filipv95** [comment]
@rossneilson ack, thank you!
