### ISSUE TITLE
Proposal Creation - able to select asset with 0 value and create Proposal 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#165]
**Description**
I have created Contributor Proposal and added Transfer&Mint action, and I selected DEX for asset, and I entered certain value in Amount field, and successfully created Proposal. Then I voted fo that option as well.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Add Proposal Title and Description 
8. Add Option 
9. Click on assed drop-down and select DXD token
10. Enter some amount in Amount Field
11. Save Action
12. Create Proposal

**Expected behavior**
I should not be able to create Proposal in the first place when selected asset has no value

**Screenrecord**
https://user-images.githubusercontent.com/37701286/181804160-54373864-6124-4a6c-8d63-8b4f8fecccb2.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Perhaps some extra validation should be added here as well

**Comment by rossneilson** [comment]
This looks like a regression from #149 @MiltonTulli can you replicate?
