### ISSUE TITLE
Add token transfer permission to dev script

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#166]
**Description**
Created Contributor Proposal with action to transfer 3 SWPR tokens to an account. FOR option had 200 SWPR tokens and AGAINST had 30 SWPR tokens. I have executed the Proposal as soon as it was possible. Got Failed state.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Create Contributor Proposal with action to transfer 3 SWPR tokens to an account 
6. Vote for option 1 ("FOR") with one account
7. Vote for option 2 ("AGAINST") with second account
8. Execute Proposal when it comes to Executable state

**Expected behavior**
Account should recieve certain amount of SWPR tokens since option 1("FOR") option had the up-vote. 

**Screenrecord**
https://user-images.githubusercontent.com/37701286/181806281-dedc50d6-8c6e-4666-8690-0e7241323396.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Filipv95** [comment]
@rossneilson In this case everything seems like the Proposal should be sucessfull, am I missing something here like e.g. config?

**Comment by rossneilson** [comment]
I am 90% sure this is a config issue, there was some confusion I think around this last week also. Lets turn this into a task to create existing permissions in the dev script to at least allow transferring of SWPR token for testing.

So tldr, this is expected but we should set permissions to make it pass in the script
