### ISSUE TITLE
Get only active proposals first

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#170]
We want to only display active proposals at the very top of a guild's page.

Function: `getActiveProposalsNow()`

Then underneath we can load all proposals just as we are doing now but of course without the ones showing in active

**Comment by dcrescimbeni** [comment]
Should we add any indicator or separator distinguishing the active proposals from the others?

**Comment by rossneilson** [comment]
Ah, meant to update this issue. I think we discussed it in a call.
We have the ability now to show all proposals and we still want this feature just on another page, do you think you could add a new page for showing all proposals that works exactly as things are now?
Then on the current page we will only show the active proposals
