### ISSUE TITLE
Bug/calls not shown under the right option

### ISSUE THREAD

**Issue by Kenny-Gin1** [DXgovernance/DAVI#173]
**Description**
The calls are not shown under the proper options as seen here: https://www.loom.com/share/70b31e94e69b4ba9bb3197300067303b

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Create Proposal with 'Vesting contract for DXD token' action
7. Go to Landing Page
8. Click on SWPRGuild box
9. See the call `create` and `approve` under two different options

**Expected behavior**
Expected the calls to be under the same option ("For")

**Screenshots**
https://www.loom.com/share/70b31e94e69b4ba9bb3197300067303b
**Device Information**

**Additional context**

**Comment by Filipv95** [comment]
@Kenny-Gin1 I reproduce the steps from above and I got broken page 504 but after refreshing I go to SWPRGuild and Proposal was created.


**Screenrecord:**
https://user-images.githubusercontent.com/37701286/182247743-5f1277f3-3b01-4214-ac17-efa2d4516900.mp4


**Screenshot:**
<img width="1440" alt="Screenshot 2022-08-01 at 23 07 32" src="https://user-images.githubusercontent.com/37701286/182247759-b532012e-f52b-419c-af63-a6a02c153c2d.png">

**Comment by Kenny-Gin1** [comment]
> @Kenny-Gin1 I reproduce the steps from above and I got broken page 504 but after refreshing I go to SWPRGuild and Proposal was created.
> 
> Also the calls are not shown under proper option as you mentioned.
> 
> **Screenrecord:** https://user-images.githubusercontent.com/37701286/182247743-5f1277f3-3b01-4214-ac17-efa2d4516900.mp4
> 
> **Screenshot:** <img alt="Screenshot 2022-08-01 at 23 07 32" width="1440" src="https://user-images.githubusercontent.com/37701286/182247759-b532012e-f52b-419c-af63-a6a02c153c2d.png">

Thanks for noticing! I ran through the code in my branch again and noticed no issues, so I am guessing that the errors happened after my merge.

I'm guessing in this merge: https://github.com/DXgovernance/DAVI/pull/164/files. @dcrescimbeni would you have time to look at it? Somewhere an infinite loop is happening when trying to create a proposal.
