### ISSUE TITLE
Get all discussions for guild and display in cards

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#176]
Blocked by #175 

Design for discussion cards:
![Screenshot 2022-08-02 at 16 18 27](https://user-images.githubusercontent.com/39137239/182410696-f9e7e62a-e0db-48b4-84ff-cd3563ced845.jpg)

We can call getPosts() by specifying the context as the guild address. In future we will do more filtering to only get the high level discussions then fetch more data but for now we can do just this. 

https://orbis-web-teal.vercel.app/developers/api-documentation/getPosts

We can set the body to a json object that includes the title then the body.

This should be infinitely scrolling for now and we will put a limit on it eventually.

We also want to poll this for new data, for now lets set that to 10 seconds and change it later. 

Reactions and replies will be 0 for now and fetched later

**Comment by rossneilson** [comment]
We have a new feature that I believe lets us get only our discussion posts and not all the replies to that discussion.

![Image](https://user-images.githubusercontent.com/39137239/183946522-9ba7f82b-ee81-4726-8589-fd24c5ed4b35.jpg)

https://orbis.club/developers/api-documentation/getPosts

**Comment by dcrescimbeni** [comment]
The margins for the proposal cards are 24px all around, but the margins for the discussion cards are 24px on the sides and 20px top/bottom. Should we unify margin sizes, or was it intentional?

Also, do the discussion card interactions on hover are the same as the proposal cards? Meaning: highlight border and content.

**Comment by rossneilson** [comment]
Will need to check with @pimato on margins but the discussion cards are meant to be more compact.

And I believe hover activity is supposed to be the same, at least it makes sense like that
