### ISSUE TITLE
Redirected to White page after creating Proposal

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#179]
**Description**
Redirected to white page after creating Proposal with single Transfer&Mint action  

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Create Proposal with 'Transfer&Mint' action
7. Approve transaction on Metamask

**Expected behavior**
After creating Proposal I should be redirected to SWPR Guilds page 

**Screenrecord**
https://user-images.githubusercontent.com/37701286/182668977-7f79bbfe-dd8f-4535-b674-bd10c1260d39.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
This was previously the bug with Proposal with 'Vesting contract for DXD token' action, also, I've noticed that after some time it stops redirecting me to white page. Not sure what's going on.
e.g. After I've opened localhost > created two same Proposals with single Transfer&Mint action > click on Create Proposal button > approving transaction on Metamask > redirected to White page

**Comment by Kenny-Gin1** [comment]
Thanks @Filipv95! I had a call with @dcrescimbeni earlier today, and we believe it was introduced during this [PR](https://github.com/DXgovernance/DAVI/pull/164). A new fix for this issue will be made by @dcrescimbeni in a bit!

**Comment by nikolajovancevic** [comment]
@Kenny-Gin1 That's awesome news!

Glad I can help!

**Comment by Filipv95** [comment]
@keny Thats’s awesome news!

Glad I can help!
