### ISSUE TITLE
'Update ENS Content' action tooltip is flickering on hover

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#189]
**Description**
On 'Update ENS content' form, when I hover tooltip icon the text is kinda flickering. 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on 'Create Proposal'
7. Click on 'Add action' button
8. Select 'Update ENS content' 
9. Hover tooltip icon

**Expected behavior**
Tooltip text should appear without flickering on hover.

**Screenrecord**
https://user-images.githubusercontent.com/37701286/183266546-87c9840a-beb0-480a-8f6e-07b13b2c5f92.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by MiltonTulli** [comment]
@dcrescimbeni 
I created a tooltip some time ago. I know can be tricky. I used a light lib for positioning stuff. 
https://gist.github.com/MiltonTulli/f2c4ee6be28052f9548e9d801ca20252
Feel free to copy any ideas from there.
