### ISSUE TITLE
Unable to create Proposal with 'Mint REP' action 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#190]
**Description**
After I've saved 'Mint REP' action, I always get rejected when click on 'Create Proposal' button 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on 'Create Proposal'
7. Add 'Mint REP' action
8. Click on 'Create Proposal' button

**Expected behavior**
Should be able to successfully create Proposal with 'Mint REP' action

**Screenrecord**
https://user-images.githubusercontent.com/37701286/183266704-84939d45-59a5-46ac-b79a-635ba44d47c2.mp4

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
After attempt to create Proposal with 'Mint REP' action failed, I've created Proposal with Transfer&Mint action successfully. Tried this couple of times with same result.

**Comment by rossneilson** [comment]
This is also likely related to issue #112 and will test once updating bytecodes

**Comment by rossneilson** [comment]
This can be tested after merging of #231

**Comment by Filipv95** [comment]
@rossneilson #231 is merged but I am still unable to create Proposal with 'Mint REP' action.

<img width="1434" alt="Screenshot 2022-08-26 at 01 18 46" src="https://user-images.githubusercontent.com/37701286/186785072-600d39af-207e-41ef-aa64-8ba345510c7d.png">

**Comment by rossneilson** [comment]
This is because the option should not be showing up here. We have an issue with identifying guild types that I am looking at

**Comment by Filipv95** [comment]
@rossneilson ack, so we are leaving this open until you fix the issue?
