### ISSUE TITLE
SWPRGuild page - 'Vesting contract for DXD token' action isn't display properly

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#191]
**Description**
Action is not visible on SWPRGuild page, on Proposal Preview page it is.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Find Proposal with 'Vesting contract for DXD token' action
7. Check information about 'Vesting contract for DXD token' action on SWPRGuilds page
7. Go to that Proposal Preview page
8. Check information about 'Vesting contract for DXD token' action Proposal Preview page

**Expected behavior**
Information about 'Vesting contract for DXD token' action should be visible

**Screenshots**
SWPRGuild page:
![vesting1](https://user-images.githubusercontent.com/37701286/183266922-fb308cf3-e01f-4431-8add-fb76ed82bd6e.png)
Proposal Preview page:
![vesting2](https://user-images.githubusercontent.com/37701286/183266924-a88ed995-27ae-4753-83ca-30876dc8ffd4.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
We had similar issue (#142) where this action text was missing while creating Proposal.

**Comment by Filipv95** [comment]
@rossneilson I've checked this issue again after merge of #193. There are differences but actions look is different on Guilds page and Proposal Preview page. 

Can you confirm that this is expected look?
![asdf](https://user-images.githubusercontent.com/37701286/183479748-a1ca33d2-d151-4a8d-89ca-c271c2c31879.png)
![asdf2](https://user-images.githubusercontent.com/37701286/183479757-9e88aec6-55a8-4d91-bc39-66a0a6916de5.png)

**Comment by rossneilson** [comment]
It seems there is a bug with approvals showing up here so will check that and make a PR but the shorter displaying of the action is expected
