### ISSUE TITLE
Enforced Binary features in base guild support

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#20]
Currently when creating a proposal in an enforced binary guild we have the against option but it shows "1 on-chain action" in the action overview. We should check for data 0x0 to address 0x0 with value 0 and mark that as 0 on chain actions

EDIT
Turning this into the issue for adapting to the new default base guild working as an enforced guild

**Comment by mprasanjith** [comment]
### Some context on this issue

**The previous behavior of the Base Guild**
- In the base guild a user could create a proposal with an arbitrary number of options.
- A proposal could have a minimum of one option to vote on.
- Voting results for the proposal is returned by an array (`totalVotes`).
- This array contained n+1 items. (n = number of options) For example, if there were two options, the array length was 3.
- The 0th index of the `totalVotes` array was unused. The remaining indexes returned the amount of votes for each option. (index 1  = votes for option 1, Index 2 = votes for option 2 and so forth.)

**Example**
>
> **Proposal: `Pick a color.` Options are Red and Blue.**
> **Result: Red has 100 Votes and Blue has 500 Votes**
> totalVotes = [0, 100, 500]
> length(totalVotes) = 3
> Index 0 is unused.

**Previous Enforced Binary Guild behavior**

- To make sure proposals has a No option, we implemented a new contract called the EnforcedBinaryGuild.
- When creating a proposal on an EnforcedBinaryGuild, a No option was automatically added as the last option to the proposal.

**Example**
> 
> **Proposal: `Pick a color.` User only submits Red and Blue options when creating the proposal.**
> **Result: Red has 100 Votes and Blue has 500 Votes. Additionally, 50 votes on No (Abstain) option.**
> totalVotes = [0, 100, 500, 50]
> length(totalVotes) = 4
> Index 0 is unused. Index 3 was automatically added, although the user didn't specify it when creating the proposal.

**The new behavior after the refactor considering audit feedback**
- In the base guild a user can still create a proposal with an arbitrary number of options.
- A proposal must have a minimum of **two** options to vote on (No option and minimum one more).
- Voting results for the proposal is still returned by an array (`totalVotes`).
- The 0th index of the `totalVotes` array (which was previously unused) is now used for **handling the No option**. The remaining indexes returns the amount of votes for each option.
- EnforcedBinaryGuilds have been completely removed as now they're redundant.

**Example**
>
> **Proposal: `Pick a color.` Options are Red and Blue.**
> **Result: Red has 100 Votes and Blue has 500 Votes. 50 votes were cast on No (Abstain) option.**
> totalVotes = [50, 100, 500]
> length(totalVotes) = 3
> Index 0 now used as the No option.

**What needs to change on the UI**

1. The Action Builder shows a No option when creating a proposal on an EnforcedBinaryGuild for informational purposes. This should now be shown on all guilds.
2. The voting box should show the 0th index as the last option when voting on a proposal. We were ignoring the 0th index before.
3. The vote results box should show the 0th index as the last option when viewing results. We were ignoring the 0th index before.
4. We need to update the `useGuildImplementationType` hook to remove EnforcedBinary statuses and add the new guild hashes to the configs.
5. Additionally, we should hide actions that have zero values for data, address and value, regardless of what the option is.
