### ISSUE TITLE
User can't create Proposal which include 'Update ENS Content' action

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#202]
**Description**
When I want to create Proposal with 'Update ENS Content' action and click on 'Create Proposal' button, then nothing happens on the FE and I see errors in the console

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button
7. Click on Add Action button at 'For' option
8. Add 'Update ENS Content' action with all required data
9. Click on 'Create Proposal' button

**Expected behavior**
I expect the Proposal should be created with all data and I expect to be able to vote at this Proposal

**Screenshot**
![photo_2022-08-11 00 31 23](https://user-images.githubusercontent.com/37701286/184031908-348cc6c1-9aac-4d6b-99d1-dfef00f5b192.jpeg)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
@Kenny-Gin1 Could you look at this? cant tell if it is because we don't have ens contracts on localhost, but seems like it shouldn't crash here regardless?
