### ISSUE TITLE
Add approve to asset setting permissions

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#203]
**User Story**
As a treasury management user I want to set permissions on assets so that they can be directly transferred but also approved and spent via function calls

**Alternative Solutions**
Similar to how we have spending calls combine 2 actions into one we need this here also. When asset permissions are set there should be two calls to the permission registry, one to set `transfer` signature and one for `approve` signature. But both should appear inside the one action on the action builder. Order is not important

**Additional context**
We currently only set transfer signature but need approve(spender, amount) also

**Comment by MiltonTulli** [comment]
I think the order is important when decoding actions we assume that the approval call is previous to the call that needs to be approved. So would be good to have the same structure. [approval, transfer]

**Comment by rossneilson** [comment]
Makes sense to do it this way but it actually doesn't matter what order we set the permissions in since it is not actually calling the approval or transfer functions

**Comment by rossneilson** [comment]
Quick update on this. After thinking and discussing with Milton I think the best way to achieve this feature will be to just create two separate actions not joined together as we haven't really architected things to be able to continue adding joint actions like with spending call.
So the new user behaviour would be:
1. User sets permissions for a token the same way they did before
2. Two actions are added "Set transfer permissions for token X" and "Set approval permissions for token X"

This should be easier to implement, cleaner in the code and actually gives the user more flexibility since they can chose to remove one of the permissions
