### ISSUE TITLE
SWPRGuild - 'Action' filters are not working as expected 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#205]
**Description**
I've created Proposals with every action possible (unable to create Proposal with some actions) and tried to filter them by 'Action' filter.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on 'Action' filter drop-down
7. Select any filter
8. Check filter results 

**Expected behavior**
Action filters should filter available Proposals by selected action.

**Screenrecord**
https://user-images.githubusercontent.com/37701286/184186987-5ae10c97-72c1-44d6-911c-0a89bf08612a.mp4

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
I think this worked previously

**Comment by Filipv95** [comment]
@rossneilson I'm pretty sure this issue existed before push (first orbis implementation #182), could be a regression of course, can we check the code regardless?

**Comment by rossneilson** [comment]
I think its a regression, hopefully will be an easy fix

**Comment by MiltonTulli** [comment]
Regression issue introduced here => https://github.com/DXgovernance/DAVI/pull/180/files#diff-96a02e05c2ebcd6d0c109b6c6dfed71102e4aaa8b5a10f655bd6cb41dad89c29L40 by removing argument from `withFilters`. 

Fix pr: https://github.com/DXgovernance/DAVI/pull/245
