### ISSUE TITLE
Landing page unable to load

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#208]
**Description**
Noticed this behavior yesterday, it just keeps on loading like on screen record. 
I did hard-refresh, git pull (up-to-date), npm -i, yarn -i

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded

**Expected behavior**
Should be able to spin up local env 

**Screenshot**
![asdf](https://user-images.githubusercontent.com/37701286/184484153-0f4dbc7c-530e-4717-8e1e-0b78fa04478c.png)
![asdf2](https://user-images.githubusercontent.com/37701286/184486941-8d88a815-b9aa-4dc3-904d-83960f55a755.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
URL changes to: http://localhost:3000/#/homestead
URL of SWPR Guild before connecting the wallet to Meta Mask: http://localhost:3000/#/localhost/0xCC88B92dcBA3003d717050dC67dDce4CBD1a3CE4

**Comment by Filipv95** [comment]
@rossneilson @Kenny-Gin1 Could this be something with config?

**Comment by rossneilson** [comment]
Your network is on ethereum, needs to be localhost.
This is actually another bug though, we should give up searching on networks where the guild registry does not exist instead of infinitely loading

**Comment by Filipv95** [comment]
@rossneilson That's right. But before when I connect my wallet I was automatically set on localhost network. When I click to switch networks to localhost nothing happens, check screen record.

https://user-images.githubusercontent.com/37701286/184525683-65437045-b874-4f80-8f8c-2a21be8fc962.mp4

**Comment by rossneilson** [comment]
I seem to only be able to replicate this by switching to localhost, can you confirm?

**Comment by Filipv95** [comment]
@rossneilson when I initially connect my wallet I'm on ETH network - previously would be localhost right away. Then I try to switch to localhost network and nothing happens - like on screen record

**Comment by Filipv95** [comment]
@rossneilson I figure it out, seems like network synch between DAPP and Metamask is not working properly - wild guess, maybe something to do with wagmi. 
After I've changed network to localhost on Metamask extension itself (this was previously done automatically) everything is back to normal.
