### ISSUE TITLE
'Transfer & Mint' action - loading of recipient icon  

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#220]
**Description**
Seem like it is loading and icon endlessly. 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask and join SWPRGuild
5. Click on 'Create Proposal' button
6. Click on 'Add action' button
7. Click on 'Transfer & Mint' action

**Expected behavior**
Some default icon for 'Etherium address' placeholder

**Screenshots**
https://user-images.githubusercontent.com/37701286/184920959-84cc72e4-af22-4a82-b70b-177f3fa9192d.mp4

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional Information**
Also visible at 'Swpr fees' action module

**Comment by rossneilson** [comment]
Nice find, solution will be to stop trying to load if we don't have an address populated
