### ISSUE TITLE
Display chosen vote once voted

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#226]
**User Story**
As a governor I want to know what I have voted for and that I do not need to do it again.

**Alternative Solutions**
Some message and no voting buttons visible
Use `getProposalVotesOfVoter` to get user voting data on a specific proposal

**Comment by MiltonTulli** [comment]
![Image](https://user-images.githubusercontent.com/25844967/189000638-fd440470-c0b3-433d-8cc4-f84ee4304fb7.png)

**Comment by rossneilson** [comment]
For the message lets say "You voted for option x with (3% / 40 SWPR)" and calculate whether to show percentage or token amount the same way we do in the voting amounts above
