### ISSUE TITLE
Transaction Rejected - unable to join the SWPRGuild   

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#247]
**Description**
Logged this since it did not happen previously, basically, I connect wallet to Metamask with first account create Proposal, vote on that Proposal. 
Then I switch to second account and when I try to join the SWPRGuild (approve SWPR tokens spending) I get transaction rejected. - this was previously not the case i.e. it worked smoothly.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask with first account
5. Create Proposal with 'Transfer & Mint' action with first account
6. Vote For that Proposal to execute successfully
7. Switch to second account
8. Connect wallet to Metamask with second account
9. Join SWPRGuild (approve SWPR tokens spending)

**Expected behavior**
I should be able to join the SWPRGuild without my transaction being rejected since I have tokens,

**Screenrecord**
https://user-images.githubusercontent.com/37701286/186778172-4fba643a-0ccf-4ea1-9e31-b61f2056c312.mp4

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
My bad, I switched out the guild for a new one under the same name and haven't sent you tokens yet
