### ISSUE TITLE
IPFS Pinata Pin

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#251]
**User Story**
As a proposer, I dont want to rely on local ipfs instance pinning to replicate and retrieve data. 

**Alternative Solutions**
If you look at dxvote we have pinata pinning services along with using the local ipfs node. We want that in DAVI too, we should use two endpoints listed below. We can also reuse the key in the file linked below. 

We should also remove the duplicated list of gateways we have currently. 

Endpoints:
- https://api.pinata.cloud/pinning/pinByHash
- https://api.pinata.cloud/pinning/pinJSONToIPFS

Example: https://github.com/DXgovernance/dxvote/blob/6f5edb30b6e727c5574750fa6831f3b9940a7656/src/services/PinataService.ts

New gateway: https://davi.mypinata.cloud/ipfs/

**Comment by dcrescimbeni** [comment]
A question to clarify some thoughts:

The idea is to pin the content both on the local node and Pinata?
