### ISSUE TITLE
Getting Generic Error message on Goerli 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#257]
**Description**
Getting Generic Error message on Goerli when there are no transactions on Swpr Guilds page, it dissapears after couple of seconds.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goerli' network
6. Go to SWPR Guild page

**Expected behavior**
Should see message ''There are no active proposals. [Go to all proposals page.]"

**Screenshots**
![genericerror](https://user-images.githubusercontent.com/37701286/187373846-8400f662-8eb0-4a2f-b78b-41da5d79411d.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
I'm having problems replicating, is this consistent?

**Comment by Filipv95** [comment]
@rossneilson no it is not, I've noticed this couple of times but also unable to rep every time.

**Comment by Filipv95** [comment]
@rossneilson Update, had this behavior again yesterday. 
Voted on Proposal > while I was waiting for transaction to pass on Metamask I got this error in the background. It's just visible for brief moment and then it disappears.
 
![goerli](https://user-images.githubusercontent.com/37701286/187864668-ce87fafb-adb9-436b-9476-be7eabb10ed5.png)
