### ISSUE TITLE
Goerli network - Multisig Guild members number not increasing

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#268]
**Description**
After I've joined Multisig Guild, number of members in the Guild remained zero.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goerli' network
6. Go to Multisig Guild page
7. Join the guild by approving and locking tokens

**Expected behavior**
Number of members should increase.

**Screenshots**
![multisig](https://user-images.githubusercontent.com/37701286/187793326-4742ea67-7833-4a9e-a871-7f33959eca31.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
The solution to this is that is we have `isRepGuild === true` then we need to instead get the total member count from the token itself by calling `getTotalHolders()`

You can find the code here
https://github.com/DXgovernance/dxdao-contracts/blob/develop/contracts/utils/ERC20/ERC20SnapshotRep.sol
https://github.com/DXgovernance/dxdao-contracts/blob/develop/contracts/erc20guild/implementations/SnapshotRepERC20Guild.sol

**Comment by Filipv95** [comment]
@rossneilson Tnx for the explanation, currently on Goerli network we have issue regarding 'Mint REP' action, that is kinda blocking my testing of this, described here #288

**Comment by rossneilson** [comment]
> 



> @rossneilson Tnx for the explanation, currently on Goerli network we have issue regarding 'Mint REP' action, that is kinda blocking my testing of this, described here #288
> 
> **Update:** I've managed to quickli click on 'Mint REP' action and add it, but still this should be fixed.
> 
> Anyway I've minted REP to first two accounts from hardhat.config.js file (**Account 0** & **Account 1**) but members number in Mutisig Guild did not increase. Both Proposals were executed successfully.
> 

The amount will not increase until this issue is fixed by @rulfo71 but you should still be able to test other ways like checking if those accounts have increased power in the guild
