### ISSUE TITLE
Goerli network - Infinite loop on Proposal page 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#269]
**Description**
I've created Proposal with 'Transfer' action, when I went to Proposal page there was infinite loop and also got some errors in the console.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goerli' network
6. Go to Multisig Guild page
7. Join the guild by approving and locking tokens
8. Create Proposal with 'Transfer' action
9. Go to newly created Proposal page

**Expected behavior**
Should see Proposals data entered while creating it.

**Screenshots**
![multisig1](https://user-images.githubusercontent.com/37701286/187793790-a615708c-3ba3-410c-9dfc-94c44bb4ee23.png)
![multisig2](https://user-images.githubusercontent.com/37701286/187793795-c7f60786-30ad-446c-a91f-65b301a510e9.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Also, I've managed to successfully vote for Proposal (option 1) and got this in Proposal description, "We ran into an error while trying to load the proposal content. Please refresh the page and try again."
![multisig3](https://user-images.githubusercontent.com/37701286/187795137-4226bf9c-2d84-4317-92fd-bed034673086.png)

**Comment by rossneilson** [comment]
Could you test this after merging #286 it should fix this (its caused by data not being properly pinned in the creation process)
