### ISSUE TITLE
Use actual winning option for proposal card winning action

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#277]
We just use a default of option 0 but we really need to calculate which vote is actually winning in ProposalCard
![Screenshot 2022-09-02 at 12 12 50](https://user-images.githubusercontent.com/39137239/188127616-ef8e789b-2463-492c-85fd-32be9a1ed136.jpg)

**Comment by MiltonTulli** [comment]
@rossneilson ProposalCardWrapper is passing down options prop as `sortedOptionsByWiningVote` so by default `options[0]` will be the first if no option has been voted or the actual winning option if anyone has voted. I tested and worked ok. 
What I can think of is handling that logic inside `ProposalCardWinningOption` so it is more clear. Any thoughts?
