### ISSUE TITLE
Goerli network - Mint REP action dissapearing from the modal

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#288]
**Description**
On Goerli network, I am on Proposal creation page, when I click on 'Add action' button then 'Mint REP' action dissapears after short period of time.   

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goreli' network
6. Go to 'Multisig Guilds' page
7. Click on 'Create Proposal' button
8. Click on 'Add action' button

**Expected behavior**
'Mint REP' action should be visible

**Screenrecord**
https://user-images.githubusercontent.com/37701286/188820629-fecdcf26-c01a-4741-a247-b61f3d815d0a.mp4

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Same behavior on demo env - https://project-davi.dev/#/goerli

**Comment by Filipv95** [comment]
**Update**
'MinREP' action actually appears in the modal but after small period of time 
![actions1](https://user-images.githubusercontent.com/37701286/193141342-29c6e719-0891-410a-9b45-a39831581a39.png)
![actions2](https://user-images.githubusercontent.com/37701286/193141348-881c8a18-c52c-4c0a-88e5-5c730f26b567.png)

**Comment by rossneilson** [comment]
Can we test this again now, it should be resolved with optimisation of how we fetch guild implementation types

**Comment by Filipv95** [comment]
Hey @rossneilson, sry for the delay on comment, this is no logner the issues test has **passed**!
