### ISSUE TITLE
Goerli network - random error appearing 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#321]
**Description**
it's hard to catch this error since it is appearing randomly on Guilds pages 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet to Metamask
5. Switch to 'Goerli' network
6. Go to SWPRGuild page

**Expected behavior**
Error should not appear for no reason

**Screenshots**
![error](https://user-images.githubusercontent.com/37701286/191051034-d3de8de2-a05a-4779-8164-278c99f93843.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Logged this issue also, not sure if they are related, Getting Generic Error message on Goerli #257

**Comment by dcrescimbeni** [comment]
This error seems to come from the `useContractRead`. Apparently, if the contract deployed doesn't have the method that the hook is fetching, it throws this.

However, I'm not able to trigger it, unless I call a method that it's effectively not present in the deployed contract.

We have another `call revert exception` error, but that doesn't seem to have any impact in the data, or trigger any error screen.

Maybe we should leave this open in case that it pops up again? I don't think this should be labeled as "frequency: high".

**Comment by dcrescimbeni** [comment]
Unnasigned it and moved to the bottom of the backlog.

**Comment by Kenny-Gin1** [comment]
@rossneilson

**Comment by rossneilson** [comment]
Thanks missed this one, nice work investigating Dino

**Comment by rossneilson** [comment]
I haven't seen this at all during extensive testing in production networks this week. Going to close and @Filipv95 feel free to repoen if you see it again.
