### ISSUE TITLE
Quorum snapshot bug

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#330]
**Description**
When we go to an older snapshotted proposal we see incorrect quorum data

**Steps to Reproduce**

1. Go to one of the first proposals in SWPR guild
2. check quorum, it should be more than 10%

**Expected behavior**
In swpr guild it should always be 10% or the number of tokens equal to 10% at the snapshotted time

**Solution**
Currently in `useVotingResults` we get quorum from `useGuildConfig` this calls `getVotingPowerForProposalExecution` with no args which is gets the current quorum requirements. However what we want in the case of `isSnapshot` guilds is to pass the snapshotId as seen in the snapshot guild contract. 
We can either make a new hook for this or make it optional param in `useGuildConfig` hook, implementer's choice

**Comment by MiltonTulli** [comment]
@rossneilson 
After debugging and trying to fix this I saw that swaprguild is not snapshot guild so not sure if this issue still valid. This is the config we have in devScript
```     
{
        token: 'SWPR',
        contractName: 'ERC20GuildUpgradeable',
        name: 'SWPRGuild',
...
```

Anyways I fixed guildConfig to use new hook `useVotingPowerForProposalExecution` to pull correct data according to guild type. 
```
 * -  ERC20GuildContract (BASE):
 *    function getVotingPowerForProposalExecution() public view virtual returns (uint256) {}
 *
 * -  SnapshotERC20Guild: (SNAPSHOT)
 *    function getVotingPowerForProposalExecution(uint256 snapshotId) public view virtual returns (uint256) {}
 *
 * -  SnapshotRepERC20Guild (SNAPSHOT-REP)
 *    function getSnapshotVotingPowerForProposalExecution(bytes32 proposalId) public view virtual returns (uint256) {}
 */
``` 

Why is that `In swpr guild it should always be 10%`? Not fully understanding and can't replicate/test. 
Should this change made (pulling correct voting power for proposal execution according to guild type) "fix" it?

**Comment by rossneilson** [comment]
Ah interesting! In that case we should definitely change our develop setup but yes this was goerli, will try to include network on future bug reports :)
