### ISSUE TITLE
Incorrect withdraw time

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#333]
**Description**
It seems our withdraw time calculations may be wrong, needs some investigation.

I think this is due to our change to increase lock time until at least after the proposal ends, perhaps we can instead try to directly read `tokensLocked` mapping from the guild contract

**Steps to Reproduce**

1. Go to SWPR guild
2. Lock tokens
3. Check how long is left until withdraw
4. Compare against expected configuration for `lockTime`
5. If time is correct try voting in a proposal, this should increase lock time

**Expected behavior**
Time to withdraw should match config and increase after voting (if voting end time exceeds previous withdraw period)

**Comment by Kenny-Gin1** [comment]
Coulnd't be reproduced.

**Comment by rossneilson** [comment]
Closing for now, cant reproduce either
