### ISSUE TITLE
Minting REP in action builder

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#335]
**Description**
Minting rep is showing us an extra action in action builder and proposals cannot be made. Likely a regression.
![Screenshot 2022-09-20 at 21 23 58](https://user-images.githubusercontent.com/39137239/191357374-b9edb20b-bb54-4dae-bfc0-246d857e01a3.jpg)

**Steps to Reproduce**

1. Go to MS guild
2. Create proposal to mint rep
3. Look at action builder and there will be duplicated actions
4. Creating will also not work

**Expected behavior**
Only for should get the rep mint aciton

**Screenshots**

**Device Information**

- Device: [e.g. PC or mobile phone version]

**Additional context**

**Comment by Filipv95** [comment]
Hey @rossneilson is this on `develop` branch, I'm unable to replicate this 

https://user-images.githubusercontent.com/37701286/191608354-b6b07d0a-b558-49bf-ab95-aa973a788c48.mp4

**Comment by rossneilson** [comment]
Hmmm, I think this might have been a poorly reported bug from beta, will close and keep an eye on it, thanks
