### ISSUE TITLE
Proposal card winning option snapshot id

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#340]
**Description**
In proposal cards we are not passing snapshot id when getting total supply and so the percentage shown is of current tokens locked amount.

**Steps to Reproduce**

1. Go to all proposals in swpr guild goerli
2. Scroll down to first proposals
4. Look at winning option percentage in the card
5. It should be a very small number, maybe rounded to 0%
6. Then click on the proposal and see the actual voted amount is a number more like 40%

**Expected behavior**
The proposal card should show the actual voted amount by taking into account snapshot id when getting total tokens locked for that proposal, we cannot use current snapshot id.

**Comment by Kenny-Gin1** [comment]
I am sporadically getting the right percentages of votes... so I am not sure that this is the actual reason. But will have to investigate a bit more!

**Comment by Kenny-Gin1** [comment]
![Image](https://user-images.githubusercontent.com/59825171/192532111-e08c4275-85ee-4e27-9157-5e80abc70d42.png)

**Comment by Kenny-Gin1** [comment]
The actual reason seems to be that we're not updating the UI when the `votingResult` is changed thus adding the dependencies to our `useEffect` solved the problem. But that also introduced performance degradations making our app lag and also stop working completely...
