### ISSUE TITLE
Discussion page implementation

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#345]
The final part of our social MVP built with orbis will be a discussion page that we link to from our discussion cards. 

Will update once we have completed finalised designs from Burak.

Scope: 
- View original post
- Create comment below
- Comment on other comments to make threads

**Comment by dcrescimbeni** [comment]
Link to the discussion page designs:

https://www.figma.com/proto/DEF0zqjGq4Ke4SiumAuxdS/Governance?page-id=0%3A1&node-id=32%3A3075&viewport=990%2C-666%2C0.24&scaling=min-zoom&starting-point-node-id=32%3A3075

**Comment by rossneilson** [comment]
Putting this on hold for now as we investigate a third party implementing this

**Comment by rossneilson** [comment]
Being implemented by Parallax network
