### ISSUE TITLE
Refactor watch flags

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#362]
**User Story**
As a user on lower power machines I want a more performant application

**Alternative Solutions**
We use `watch` in wagmi hooks to update data each block but is pretty inefficient especially on faster networks.
Instead, we can use`useContractEvent` to listen for events from our guild contracts and then upon receiving those events we call `refetch` from our current hooks.
https://wagmi.sh/docs/hooks/useContractEvent
To do this look at where we use `watch` right now and then work out what events are fired when we expect this value to change. 

**Acceptance criteria:**
We should test each hook and have another user do an action which would change data (vote, lock tokens, create proposal, execute proposal) and see if we see the app update the data correctly. 

**Additional context**
To test better you can change localhost block time back to 500 ms and see if the app crashes

**Comment by rossneilson** [comment]
@Kenny-Gin1 found the event hooks and gave them a quick try

**Comment by Kenny-Gin1** [comment]
Tips on how to use `useContractRead` and `useContractEvent` https://blog.softbinator.com/listen-blockchain-events-wagmi/
