### ISSUE TITLE
Proposal creation - Transfer action name is different on two modals 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#388]
**Description**
Transfer action name is different on two modals 

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Connect wallet to Metamask
4. Switch to 'Goerli' network
5. Go to SWPRGuild page
6. Click on 'Create Proposal'
7. Click on 'Add action'
8. Click on 'Transfer'

**Expected behavior**
Unified call of the action

**Screenshots**
![transfer](https://user-images.githubusercontent.com/37701286/194426658-fbbb4ecd-c371-4890-8424-3eab8ffd397b.png)
![transfer2](https://user-images.githubusercontent.com/37701286/194426662-6d19a530-9294-4bb2-806d-06c78b9f1abd.png)

**Device Information**
OS: MacOs
Browser: GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Fixed in #471
