### ISSUE TITLE
Design - Social chat MVP - Mobile view

### ISSUE THREAD

**Issue by rossneilson** [DXgovernance/DAVI#417]
We have our discussion component design but not a good mobile version.

The reddit mobile application can likely be used as a good reference here as it tackles the same problems.

**Comment by borisblock3007** [comment]
Started updating discussion component designs in mobile version first. Used references to simplify it and make it a bit easier on the eyes. Here is a screenshot of a design progress from left to right:

![Image](https://user-images.githubusercontent.com/25454493/202448562-a105ea9e-9dd8-4a17-8bd7-ecc7934354ef.png)

Next step is to create desktop versions and keep progressing with mobile view.

Link to figma file : https://www.figma.com/file/EttR9KZTQUrirqMDmI3fQv/DAVI-Dapp-Draft?node-id=0%3A1
