### ISSUE TITLE
Refactor web3 wallet and network integration

### ISSUE THREAD

**Issue by mprasanjith** [DXgovernance/DAVI#69]
After splitting the DAVI and dxvote repos, there's a lot of legacy code left in the DAVI repo around the web3 integration. We should refactor and cleanup the existing code, with a focus on making it simpler and easier to maintain.

We should also look at upgrading to web3-react v8 or wagmi. Both of these libraries are hooks-first, and better suits our current architecture better,

**Comment by rossneilson** [comment]
I think we will go for wagmi (https://www.npmjs.com/package/wagmi) and begin initially using it for wallet connect and maybe ens support and later look into using it for more data fetching
