### ISSUE TITLE
Create Guild button is disabled

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#72]
**Description**
Create Guild button is disabled and doesn't respond to a click. User should be able to click on Create Guild button and to be redirected to Create Guild Page

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Create Guild button should not be present

**Expected behavior**
Create Guild button should not be visible on Landing Page 

**Screenshots**
<img width="930" alt="Screenshot 2022-06-27 at 15 40 17" src="https://user-images.githubusercontent.com/37701286/175955520-70954785-7aa4-4866-9ac0-83a3e3158d61.png">

**Device Information**

- OS: MacOs 
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
This button should not be present and atm it redirects to broken page

**Comment by rossneilson** [comment]
Likely we will remove this for initial release, alternatively perhaps we could make a coming soon page
