### ISSUE TITLE
Search Guild field bar don't work

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#73]
**Description**
When user click on Search Guild field bar, then can see cursor next to magnifying glass icon. But when user enter some word, that word doesn't appear in field. User should be able to submit word and to see results from search.

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on Search Guild field bar
5. Enter name of Guild which you want to search

**Expected behavior**
Word which enter appear in Search Guild field bar. User can search it when press 'Enter', and should see search results.

**Actual behavior**
Word which enter don't appear in Search Guild field bar and User can't search it

**Screenshots**
<img width="930" alt="Screenshot 2022-06-27 at 18 40 54" src="https://user-images.githubusercontent.com/37701286/175991979-b6bc870b-d76f-4d45-a7aa-b34ec3b03e39.png">

**Device Information**

- OS: MacOs
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
Expect from Search bar to work and can do some input

**Comment by rossneilson** [comment]
Nice, I dont think we had an issue for this. Likely I think we will remove this UI element for initial release and add it back later with actual search functionality (mainly since we wont have many guilds initially on this page)
