### ISSUE TITLE
View on Block Explorer hyperlink not working

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#75]
**Description**
After user hase connected his wallet to MetaMask he should be able to inspect his account on Block Explorer

**Steps to Reproduce**

1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on Account address icon
6. Click on View on Block Explorer hyperlink

**Expected behavior**
User should be redirected to explorer

**Actual behavior**
Redirected to Landing page of Guilds

**Screenshots**
<img width="392" alt="Screenshot 2022-06-27 at 18 55 24" src="https://user-images.githubusercontent.com/37701286/175994891-91f4ee27-fae9-429f-ac1e-9f0e4f6a309c.png">

**Device Information**

- OS: MacOs
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
Just wondering, do we have some explorer where user need to be redirected or it's in WIP? If it's in WIP, this is not a bug just feature

**Comment by rossneilson** [comment]
We do have an explorer in localhost but we haven't fully configured it yet. Its called ethernal and I believe we first have to set up payments for the team to use it since it is an additional product. But once we have it we can test and make sure this link goes to the local explorer.

**Comment by rossneilson** [comment]
This is working on non localhost networks
