### ISSUE TITLE
REPGuild page - Settings button redirection not working				

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#78]
**Description**:					
When on any Guild page user should be able to access the settings page of that Guild					
					
**Steps to Reproduce**:					
1. SpinUp Localhost env					
2. Open localhost:3000					
3. Check if Landing Page is loaded					
4. Click on REPGuild box					
5. Click on Settings button					
					
**Actual behaviour**: 					
Redirected to Landing page					
					
**Expected behavior**:					
User should be redirected to Guilds Settings page					
					
**Screenshots**:					
<img width="252" alt="Screenshot 2022-06-29 at 22 23 53" src="https://user-images.githubusercontent.com/37701286/176537922-2254b97d-dfb5-46ac-aa6a-15eabe65f770.png">

**Device Information**

- OS: MacOs
- Browser GoogleChrome, Brave
- Device: MacOS Monterey v12.4

**Additional context**
The same behaviour is for the all Guilds. This is an feature that is not developed or connected, it's not a bug

**Comment by rossneilson** [comment]
For now we dont have this page and I will instead write issues to implement it once we have it
