### ISSUE TITLE
Voting for option on some proposal does not work as expected 

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#87]
**Description**
When I select option to vote for, confirm transaction i do not see any changes on proposal page, under vote section 

**Steps to Reproduce**
1. SpinUp Localhost env  
2. Open localhost:3000  
3. Check if Landing Page is loaded  
4. Click on DXDGuild box
5. Click on Active Proposal
6. Select the option to vote for and confirm transaction 
7. "Vote on proposal [proposal name]" transaction is visible under recent transaction 

**Expected behavior**
Vote should impact the selected option on vote section, there should be visible change 

**Actual behavior**
No visible changes on voting section, not even after page refresh

**Screenshots**
![dxd1](https://user-images.githubusercontent.com/37701286/177185468-c7f2c5f6-f932-46f7-ad9f-51fdbb2ed95e.png)
![dxd2](https://user-images.githubusercontent.com/37701286/177185480-fa52fead-bfcf-4dae-b581-8adea1b56d21.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
Transaction is visible under Recent transactions (top-right corner, account address icon)

**Comment by rossneilson** [comment]
I think this was fixed some time ago, has been working in happy path
