### ISSUE TITLE
Creating proposal - extra actions appears on proposal page

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#89]
**Description**
Given I am creating proposal and I create two actions for proposal, then on Proposal page, I notice that third action has been added automaticallly 				
				
**Steps to Reproduce**
1. SpinUp Localhost env 
2. Open localhost:3000 
3. Check if Landing Page is loaded   
4. Click on SWPRuild box 
5. Click on Create Proposal button 
6. Choose Contributer payment
7. Add two option with actions 
8. Click on Create proposal button
9. Go to newly created proposal page   

**Expected behavior**
On Proposal page there should be a number of actions that was added while creating proposal itself

**Actual behavior**
Third action appears as voting option without being added previoulsy when creating proposal

**Screenshots**
![dxd1](https://user-images.githubusercontent.com/37701286/177191443-88a2bca7-5d56-4048-aad4-94ab229f41d0.png)
![dxd2](https://user-images.githubusercontent.com/37701286/177191451-bd16be23-6d47-4a7b-ac9e-bf64e6916693.png)
![dxd3](https://user-images.githubusercontent.com/37701286/177191457-80ac7e9b-a198-4353-8b8d-65a043099eae.png)

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
This happens when I create proposal in any Guild

**Comment by rossneilson** [comment]
The default behaviour now is to see a default "For" and "Against" in the action builder. 
The for can be edited in name and actions and is just a placeholder. 
The against cannot be edited and must always be there, it will always do nothing.
You can also add more options beyond those two
