### ISSUE TITLE
Missing Members icon and Information button

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#93]
**Description**
Members are displayed below Guild title, but should be displayed at top-left corner of Guild main box.
Information button is missing. Should be displayed at top right corner of Guild main box.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box

**Expected behavior**
<img width="713" alt="dao1" src="https://user-images.githubusercontent.com/37701286/177221315-5b16b99b-76d8-4abb-a6c4-f6ae0fef8d14.png">

**Actual behavior**
<img width="1245" alt="dao2" src="https://user-images.githubusercontent.com/37701286/177221318-0d475aef-f719-4592-9de2-9c223c923dd3.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by Kenny-Gin1** [comment]
Hey @Filipv95! Thanks for notifying! Do you know what **Information** should display after clicking it? Any links to the design?

**Comment by Filipv95** [comment]
Hey @Kenny-Gin1 I'm not sure what information should be displayed after clicking "Information" button, if I had to guess, some Guild relevant data. @rossneilson do you maybe have more info on this? 

I was looking/testing this figma design:
https://www.figma.com/file/cjLng0AbOKuDj9r5oZVDmR/Wireframe?node-id=3332%3A15606

**Comment by rossneilson** [comment]
Which button?

**Comment by Filipv95** [comment]
@rossneilson '**Information**' button, check 'Expecated behavior' screenshot - you can also see it on figma link in my previous comment

**Comment by rossneilson** [comment]
![Screenshot 2022-08-16 at 14 13 32](https://user-images.githubusercontent.com/39137239/184888297-9b39a8bf-7ba6-4bc7-ab1d-5cac8c7bd13a.jpg)
