### ISSUE TITLE
Remove unused options from list

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#94]
**Description**
Options from left box menu at Guild page are different than Figma design.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Click on SWPRGuild box

**Expected behavior**
At left box menu I should see:
- Proposals
- Treasury
- Settings
<img width="893" alt="dao1" src="https://user-images.githubusercontent.com/37701286/177221694-406e5d01-4cee-4873-8b2f-78f195fa05fc.png">

**Actual behavior**
At left box menu I can see:
- Proposals
- Members
- Portfolio
- Settings
<img width="1305" alt="dao2" src="https://user-images.githubusercontent.com/37701286/177221701-72c461ae-6938-4c55-bcb4-c07d72d407b5.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Additional context**
The same behaviour is for the all Guilds.

**Comment by rossneilson** [comment]
For now I am going to turn this task into removing the options we do not use. For release I think we may still add a settings page but the rest except for proposals can go.
THe list should have only 
- Proposals
- Settings
