### ISSUE TITLE
Figma - Naming for creating Signal Proposal differs from design

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#95]
**Description**
Naming for creating Signal Proposal is actually different then Figma design

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button

**Expected behavior**
Signal
<img width="859" alt="dao1" src="https://user-images.githubusercontent.com/37701286/177221967-dd0b5cb5-36da-470b-84aa-6c8f1949fb7c.png">

**Actual behavior**
Signal Proposal
<img width="1408" alt="dao2" src="https://user-images.githubusercontent.com/37701286/177221979-cb05bdca-8dda-4458-aebf-6ccb0c2ee489.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Since these are all proposals anyways the use of "Signal proposal" is a little redundant so in this case I think the implementation is better
