### ISSUE TITLE
Figma - The order of proposals differs from design

### ISSUE THREAD

**Issue by Filipv95** [DXgovernance/DAVI#97]
**Description**
Places of Contributor Payment and Mint Reputation have been swapped.

**Steps to Reproduce**
1. SpinUp Localhost env
2. Open localhost:3000
3. Check if Landing Page is loaded
4. Connect wallet
5. Click on SWPRGuild box
6. Click on Create Proposal button

**Expected behavior**
1. Signal
2. Transfer Funds
3. Mint Reputation
4. Contributor Payment
5. Custom Proposal
<img width="859" alt="dao1" src="https://user-images.githubusercontent.com/37701286/177222567-62cece79-2cae-46d3-806d-8715c131d317.png">

**Actual behaviour**:
1. Signal Proposal
2. Transfer Funds
**3. Contributer Payment**
**4. Mint Reputation**
5. Custom Proposal
<img width="1295" alt="dao2" src="https://user-images.githubusercontent.com/37701286/177222588-c0010488-e82b-4089-81f7-8c8847b03cbc.png">

**Device Information**
OS: MacOs
Browser GoogleChrome, Brave
Device: MacOS Monterey v12.4

**Comment by rossneilson** [comment]
Going to close this as these are placeholders and should be removed ahead of initial release #99
